### ISSUE TITLE
Bot not work

### ISSUE THREAD

**Issue by dojyaaa-n** [Push911/Discord-DreamBot#2]
Hey! I really liked your discord bot! But I can't install it in any way, and when I enter a command, it says that the command was not found. I'm still new to Python, can you help)?

**Comment by RideTheSkyP** [comment]
Thank you for reporting:) Issue was: outdated youtube-dl version, I've updated requirements, so now everything must work. In case of other issues feel free to contact me)
I will continue to develop bot, have some ideas to improve it)

**Comment by dojyaaa-n** [comment]
When starting the bot, launch immediately bot.py, or make a separate folder cogs? If it's not difficult for you, can you give your discord? It will be more convenient to communicate there :)

**Comment by dojyaaa-n** [comment]
Outdated youtube-dl version

The funny thing is that I have the newest version

**Comment by RideTheSkyP** [comment]
To launch bot you need to run bot.py.
My discord: Push#6627)
